In [3]:
import torch
import numpy as np


In [4]:
 dd =np.array(
     [
     [1,2,3],
     [4,5,6],
     [7,8,9]
     ]
     )
 print(dd)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
x_data = torch.tensor(dd)
print(x_data)

print(x_data.shape)
x_data.reshape(1,9)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [6]:
t = torch.tensor([[1,2],[3,4]])
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [6]:
#Tensors from numpy

array1 = np.array([[1,2],[2,3]])
print(torch.tensor(array1).dtype)
print(torch.Tensor(array1).dtype)
print(torch.as_tensor(array1).dtype)        
print(torch.from_numpy(array1).dtype)




torch.int64
torch.float32
torch.int64
torch.int64


In [7]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
torch.zeros(3,3)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
t = torch.tensor(
    [
        [1,1,1,1],
        [2,2,2,2],
        [3,3,3,3],
        [4,4,4,4]
    ],dtype= torch.float32
)


In [12]:
print(t.reshape(1,16).squeeze())
print(t.reshape(1,16).squeeze().unsqueeze(dim=0))

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.]])


In [13]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t 

In [14]:
print(t)
print(t.reshape(1,16))
print(flatten(t))

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.]])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.])


In [15]:
t1 = torch.tensor([[1,2],[2,3]])
t2 = torch.tensor([[5,6],[7,8]])
print(torch.cat((t1,t2),dim = 0))

tensor([[1, 2],
        [2, 3],
        [5, 6],
        [7, 8]])


In [19]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
])
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])
t4 = torch.stack((t1,t2,t3),dim = 0)
print(t4.shape)

torch.Size([3, 3, 4])


In [20]:
t4 = t4.reshape(3,1,3,4)
print(t4)
print(t4.shape)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])
torch.Size([3, 1, 3, 4])


In [21]:
print(t4.flatten(start_dim =1))
print(t4.flatten(start_dim =1).shape)


tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])
torch.Size([3, 12])


In [26]:
#element wise operations 
t1 = torch.tensor([
    [1,2],
    [2,3]
],dtype = torch.float32)

t2 = torch.tensor([
    [3,4],
    [5,6]
],dtype = torch.float32)
print(t1+t2)



tensor([[4., 6.],
        [7., 9.]])


Elecment wise operations 
1. t1 + 2
2. t1 - 2 
3. t1 * 3(scalar are multiplied using broadcast function)

Broad cast function in numpy is 

In [29]:
np.broadcast_to(2,t1.shape)  
# will convert to the same shape as t1 and do elecment wise multiplication 

array([[2, 2],
       [2, 2]])

In [30]:
#what is elements are in different in size
t1 = torch.tensor([
    [1,1],
    [2,2]
],dtype= torch.float32)

t2 = torch.tensor([
    [2,3]
],dtype=torch.float32)

print(t1+t2)

tensor([[3., 4.],
        [4., 5.]])


##same name 
Elementwise operations
componentsie operations
point wise operations

some of the comapring operations 
Brocast link 
https://deeplizard.com/learn/video/6_33ulFDuCg


In [34]:
#Tensor reduction operations
# manage our tensors and datastructors

t1 = torch.tensor([
    [2,3,2],
    [3,4,3],
    [4,5,3]
],dtype = torch.float32)

print(t1.sum())
print(t1.sum().numel())
print(t1.numel())
print(t1.sum().numel() < t1.numel())

tensor(29.)
1
9
True


In [35]:
#Some other reduction operations
t1.sum()
t1.prod()
t1.mean()
t1.median() 
t1.std()
t1.abs()


tensor([[2., 3., 2.],
        [3., 4., 3.],
        [4., 5., 3.]])

In [36]:
# Row wise and col wise reduction operations
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
])


In [38]:
#colume wise sum
print (t.sum(dim = 0))
#rowwise sum
print (t.sum(dim = 1))
#overall sum 
print(t.sum())

tensor([10, 10, 10, 10])
tensor([ 4,  8, 12, 16])
tensor(40)


Arg max function - used to identy the idx of the maximum element
arg max works with row and col wise operations 

In [47]:
t = torch.tensor([
    [1,0,0,2],
    [2,3,1,0],
    [0,2,3,5]
],dtype = torch.float32)

print(t.argmax(dim = 0))
print(t.argmax(dim = 1))
print(t.max())
print(t.max(dim = 0))
print(t.max(dim = 1))


tensor([1, 1, 2, 2])
tensor([3, 1, 3])
tensor(5.)
torch.return_types.max(
values=tensor([2., 3., 3., 5.]),
indices=tensor([1, 1, 2, 2]))
torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))


In [48]:
# To access inidivitual value from the tensor use ITEM function 
print(t.mean())
print(t.mean().item())

tensor(1.5833)
1.5833333730697632


In [49]:
# to extract multiple values from the tensor
# use tolist() function 
# use   numpy()
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=0).tolist())
print(t.mean(dim=0).numpy()) 

tensor(1.5833)
tensor([1.0000, 1.6667, 1.3333, 2.3333])
[1.0, 1.6666666269302368, 1.3333333730697632, 2.3333332538604736]
[1.        1.6666666 1.3333334 2.3333333]


MNIST Dataset

Modified National institude of standards and technology 
Hand writtern chars 
it contains 70,000 dataset 
60,000 - Training 
10,000 - Testing Dataset 

MINIST Fashion - 10 class of fashion 
it contains 70,000 dataset 
60,000 - Training 
10,000 - Testing Dataset 

Torch vision - computer vision pytorch library 
Project contains 
1. prepare data
2. Build Model
3. Train the model 
4. Analyze the model

ETL 

E - Extract 
T - Transform
L - Load
