In [ ]:
from platform import python_version
print(python_version())

3.8.10


In [ ]:
!python --version

Python 3.8.10


In [18]:
#Matrix multiplication 

import numpy as np

a = [[2,3,2],
     [2,4,2],
     [3,5,3]]
print(len(a))

b = [[2,4,3],
    [3,2,2],
    [3,5,2]]
print(len(b))
out = np.zeros((3,3))
for i in range(len(a)):
    for j in range(len(b)):
        for k in range (len(b)):
            out[i][j] += a[i][k] * b[j][k]

print(out)

3
3
[[22. 16. 25.]
 [26. 18. 30.]
 [35. 25. 40.]]


In [23]:
# create class 
class fruit():
    def __init__(self):
        print("I am fruit")
class Mango(fruit):
    def __init__(self):
        super().__init__()
        print('i am mango')

myFruit = Mango()


I am fruit
i am mango


In [24]:
import pickle
expl_dict = {1:"6",2:"4",3:"5",4:"9"}

pickle_out = open("dict_pickle","wb")
pickle.dump(expl_dict,pickle_out)
pickle_out.close()



In [25]:
import pickle
pickle_in = open("dict_pickle","rb")
dict_out = pickle.load(pickle_in)
print(dict_out)
pickle_in.close()

{1: '6', 2: '4', 3: '5', 4: '9'}


In [34]:
#Zip function 
l1 = ['arang', 'mani']
l2 = ['rajan','kandan']
z1 = zip(l1,l2)
print(list(z1))

for a,b in zip(l1,l2):
    print(a,b)

list_zip = list(zip(l1,l2))
print(list_zip)

dict_zip = dict(zip(l1,l2))
print(dict_zip)

l1 = 2,4,2,5,23,24,23
l2 = 12,2,4,24,2,1,4

for a,b in zip(l1,l2):
    print( '{} + {} = {}'.format(a,b,a+b))

[('arang', 'rajan'), ('mani', 'kandan')]
arang rajan
mani kandan
[('arang', 'rajan'), ('mani', 'kandan')]
{'arang': 'rajan', 'mani': 'kandan'}
2 + 12 = 14
4 + 2 = 6
2 + 4 = 6
5 + 24 = 29
23 + 2 = 25
24 + 1 = 25
23 + 4 = 27


In [ ]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim

class Network(nn.module):
    def __int__(self):
        super.__init__()
        self.conv1 = nn.Conv2d(in_channels= 6,out_channels= 12,kernel_size=3)
        self.conv2 = nn.Conv2d(in_channels= 6,out_channels= 12,kernel_size=3)
        self.conv3 = nn.Conv2d(in_channels= 6,out_channels= 12,kernel_size=3)
        self.fc1 = nn.Linear(in_features = 128,out_features = 256)
        self.fc2 = nn.Linear(in_features = 256,out_features = 512)
        self.out = nn.Linear(in_features = 512,out_features = 5)

    def forward(self,t):
        t = t;
        t1 = self.conv1(t)
        nn.ReLU(t1)
        nn.MaxPool2d(t1)
        t2 = self.conv2(t1)
        nn.ReLU(t2)
        nn.MaxPool2d(t2)
        t3 = self.conv2(t2)
        nn.ReLU(t3)
        nn.MaxPool2d(t3)
        t4 = self.fc1(t3)
        t5 = self.fc2(t4)
        output = self.out(t5)






